-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 21:47:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mkr_rent_a_car
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mkr_rent_a_car
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mkr_rent_a_car` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mkr_rent_a_car` ;

-- -----------------------------------------------------
-- Table `mkr_rent_a_car`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkr_rent_a_car`.`CLIENTE` (
  `Id` INT(5) NOT NULL,
  `c_senha` VARCHAR(8) NOT NULL,
  `c_nome` VARCHAR(60) NOT NULL,
  `c_end` VARCHAR(60) NOT NULL,
  `c_email` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `C_email_UNIQUE` (`c_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkr_rent_a_car`.`LOCACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkr_rent_a_car`.`LOCACAO` (
  `id_loca` INT(5) NOT NULL,
  `l_codveic` VARCHAR(5) NOT NULL,
  `l_codcli` VARCHAR(5) NOT NULL,
  `l_dta_retirada` VARCHAR(10) NOT NULL,
  `l_dta_devolve` VARCHAR(10) NOT NULL,
  `l_valor` VARCHAR(6) NOT NULL,
  `l_obs` VARCHAR(100) NOT NULL,
  `CLIENTE_Id` INT(5) NOT NULL,
  PRIMARY KEY (`id_loca`, `CLIENTE_Id`),
  INDEX `fk_LOCACAO_CLIENTE_idx` (`CLIENTE_Id` ASC),
  CONSTRAINT `fk_LOCACAO_CLIENTE`
    FOREIGN KEY (`CLIENTE_Id`)
    REFERENCES `mkr_rent_a_car`.`CLIENTE` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkr_rent_a_car`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkr_rent_a_car`.`VEICULO` (
  `id_car` INT(5) NOT NULL,
  `c_mod` VARCHAR(5) NOT NULL,
  `c_ano` VARCHAR(4) NOT NULL,
  `c_cor` VARCHAR(15) NOT NULL,
  `c_desc` VARCHAR(50) NOT NULL,
  `c_obs` VARCHAR(150) NOT NULL,
  `LOCACAO_id_loca` INT(5) NOT NULL,
  `LOCACAO_CLIENTE_Id` INT(5) NOT NULL,
  PRIMARY KEY (`id_car`, `LOCACAO_id_loca`, `LOCACAO_CLIENTE_Id`),
  INDEX `fk_VEICULO_LOCACAO1_idx` (`LOCACAO_id_loca` ASC, `LOCACAO_CLIENTE_Id` ASC),
  CONSTRAINT `fk_VEICULO_LOCACAO1`
    FOREIGN KEY (`LOCACAO_id_loca` , `LOCACAO_CLIENTE_Id`)
    REFERENCES `mkr_rent_a_car`.`LOCACAO` (`id_loca` , `CLIENTE_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkr_rent_a_car`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkr_rent_a_car`.`MARCA` (
  `id_mar` INT(5) NOT NULL AUTO_INCREMENT,
  `mc_desc` VARCHAR(150) NOT NULL,
  `mc_ativo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_mar`),
  UNIQUE INDEX `mc_desc_UNIQUE` (`mc_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mkr_rent_a_car`.`MODELO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mkr_rent_a_car`.`MODELO` (
  `id_model` INT(5) NOT NULL AUTO_INCREMENT,
  `md_desc` VARCHAR(150) NOT NULL,
  `MARCA_id_mar` INT(5) NOT NULL,
  `VEICULO_id_car` INT(5) NOT NULL,
  PRIMARY KEY (`id_model`, `MARCA_id_mar`, `VEICULO_id_car`),
  INDEX `fk_MODELO_MARCA1_idx` (`MARCA_id_mar` ASC),
  INDEX `fk_MODELO_VEICULO1_idx` (`VEICULO_id_car` ASC),
  CONSTRAINT `fk_MODELO_MARCA1`
    FOREIGN KEY (`MARCA_id_mar`)
    REFERENCES `mkr_rent_a_car`.`MARCA` (`id_mar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MODELO_VEICULO1`
    FOREIGN KEY (`VEICULO_id_car`)
    REFERENCES `mkr_rent_a_car`.`VEICULO` (`id_car`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
